### ISSUE TITLE
cnetos 实测无法执行

### ISSUE THREAD

**Issue by babyshen** [ProbiusOfficial/bashFuck#1]
![image](https://user-images.githubusercontent.com/11402197/231639506-3acc46a7-131b-4e41-9752-533f4dc7be2d.png)

![image](https://user-images.githubusercontent.com/11402197/231639532-ec0b6ff1-1c60-4c6e-8634-9a72a82b96cc.png)

执行报错

**Comment by ProbiusOfficial** [comment]
![image](https://user-images.githubusercontent.com/41804496/231735248-b2a199e9-611b-485f-a11f-f907eade8088.png)
![image](https://user-images.githubusercontent.com/41804496/231736085-77ad3426-3daf-41d4-88d5-06ea1e5032e7.png)
因为连入时ssh的$0变量指向的是-bash 而不是 bash
在 CentOS 中，当您通过 SSH 登录时，$0 可能会指向 -bash 而不是 bash。这是因为登录 shell 会将其名称前加上一个 -，这表示这个 shell 是一个登录 shell。这个约定通常用于区分登录 shell 和非登录 shell。

登录 shell 和非登录 shell 的主要区别在于它们读取和执行的配置文件。登录 shell 通常在启动时读取 /etc/profile、~/.bash_profile、~/.bash_login 和 ~/.profile（按顺序）。而非登录 shell 只会读取 ~/.bashrc。

当您通过 SSH 登录时，系统会启动一个登录 shell，因此 $0 会指向 -bash。这并不是错误或异常情况，而是一个正常的行为。如果您在本地终端启动一个新的 shell，您可能会发现 $0 指向 bash 而不是 -bash，因为这个新 shell 是一个非登录 shell。
